global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Axwabo.CommandSystem.Attributes;
global using Axwabo.CommandSystem.Attributes.Targeting;
global using Axwabo.CommandSystem.Commands;
global using Axwabo.CommandSystem.Commands.Interfaces;
global using Axwabo.CommandSystem.Permissions;
global using Axwabo.Helpers;
global using LabApi.Features.Wrappers;
global using ModeratorTools.Attributes;
global using UnityEngine;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
